### ISSUE TITLE
How to wait for Input.GetMouseButtonDown

### ISSUE THREAD

**Issue by takaaptech** [FilamentGames/BeauRoutine#1]
Hi @BeauchesneFilament!
Firstly, thank so much for such an awesome project! It is very clean and new way to code unity that I love so much!
From your example, I see some extension like:
yield return m_RestartButton.onClick.WaitForInvoke();
Now I want to wait for the user to click on the scene. I am thinking about the wait for Input.GetMouseButtonDown but I do not know how to get this
Can you give me an example of how to handle that?
Thank so much!

**Comment by BeauchesneFilament** [comment]
Hey @takaaptech! Glad you're finding BeauRoutine useful!

There are a couple different ways you could achieve this.
```csharp
// Inline waiting for mouse input
while(!Input.GetMouseButtonDown(0))
   yield return null;

// Using Routine.WaitCondition with an anonymous function
// Note that there will be a single-frame delay before any checks for mouse input are made
yield return Routine.WaitCondition(() => Input.GetMouseButtonDown(0));
```
Unfortunately, C# doesn't allow me to add extension methods to static classes, so an `Input.WaitForMouseButtonDown` can't be written as such, but creating your own utility functions that wrap one of the above methods should be straightforward enough. I'd recommend wrapping the first method over the second, as it involves fewer nested coroutines and is therefore _slightly_ more responsive.

**Comment by takaaptech** [comment]
Thanks @BeauchesneFilament !
